// Code generated by MockGen. DO NOT EDIT.
// Source: leaderboard_repository.go
//
// Generated by this command:
//
//	mockgen -source=leaderboard_repository.go -destination=leaderboard_repository_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	reflect "reflect"

	models "github.com/lauralesteves/copa-guru-backend/internal/models"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaderboardRepository is a mock of LeaderboardRepository interface.
type MockLeaderboardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaderboardRepositoryMockRecorder is the mock recorder for MockLeaderboardRepository.
type MockLeaderboardRepositoryMockRecorder struct {
	mock *MockLeaderboardRepository
}

// NewMockLeaderboardRepository creates a new mock instance.
func NewMockLeaderboardRepository(ctrl *gomock.Controller) *MockLeaderboardRepository {
	mock := &MockLeaderboardRepository{ctrl: ctrl}
	mock.recorder = &MockLeaderboardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardRepository) EXPECT() *MockLeaderboardRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockLeaderboardRepository) Count() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockLeaderboardRepositoryMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockLeaderboardRepository)(nil).Count))
}

// GetByUserID mocks base method.
func (m *MockLeaderboardRepository) GetByUserID(userID bson.ObjectID) (*models.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*models.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockLeaderboardRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockLeaderboardRepository)(nil).GetByUserID), userID)
}

// List mocks base method.
func (m *MockLeaderboardRepository) List(limit, offset int64) ([]*models.LeaderboardEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", limit, offset)
	ret0, _ := ret[0].([]*models.LeaderboardEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockLeaderboardRepositoryMockRecorder) List(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLeaderboardRepository)(nil).List), limit, offset)
}

// ReplaceAll mocks base method.
func (m *MockLeaderboardRepository) ReplaceAll(entries []*models.LeaderboardEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAll", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAll indicates an expected call of ReplaceAll.
func (mr *MockLeaderboardRepositoryMockRecorder) ReplaceAll(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAll", reflect.TypeOf((*MockLeaderboardRepository)(nil).ReplaceAll), entries)
}
