// Code generated by MockGen. DO NOT EDIT.
// Source: google_oauth.go
//
// Generated by this command:
//
//	mockgen -source=google_oauth.go -destination=google_oauth_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGoogleOAuthClient is a mock of GoogleOAuthClient interface.
type MockGoogleOAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleOAuthClientMockRecorder
	isgomock struct{}
}

// MockGoogleOAuthClientMockRecorder is the mock recorder for MockGoogleOAuthClient.
type MockGoogleOAuthClientMockRecorder struct {
	mock *MockGoogleOAuthClient
}

// NewMockGoogleOAuthClient creates a new mock instance.
func NewMockGoogleOAuthClient(ctrl *gomock.Controller) *MockGoogleOAuthClient {
	mock := &MockGoogleOAuthClient{ctrl: ctrl}
	mock.recorder = &MockGoogleOAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleOAuthClient) EXPECT() *MockGoogleOAuthClientMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockGoogleOAuthClient) Exchange(ctx context.Context, code, redirectURI string) (*GoogleUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, code, redirectURI)
	ret0, _ := ret[0].(*GoogleUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockGoogleOAuthClientMockRecorder) Exchange(ctx, code, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockGoogleOAuthClient)(nil).Exchange), ctx, code, redirectURI)
}
