// Code generated by MockGen. DO NOT EDIT.
// Source: leaderboard_service.go
//
// Generated by this command:
//
//	mockgen -source=leaderboard_service.go -destination=leaderboard_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	models "github.com/lauralesteves/copa-guru-backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaderboardService is a mock of LeaderboardService interface.
type MockLeaderboardService struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardServiceMockRecorder
	isgomock struct{}
}

// MockLeaderboardServiceMockRecorder is the mock recorder for MockLeaderboardService.
type MockLeaderboardServiceMockRecorder struct {
	mock *MockLeaderboardService
}

// NewMockLeaderboardService creates a new mock instance.
func NewMockLeaderboardService(ctrl *gomock.Controller) *MockLeaderboardService {
	mock := &MockLeaderboardService{ctrl: ctrl}
	mock.recorder = &MockLeaderboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardService) EXPECT() *MockLeaderboardServiceMockRecorder {
	return m.recorder
}

// GetLeaderboard mocks base method.
func (m *MockLeaderboardService) GetLeaderboard(limit, offset int64) ([]*models.LeaderboardEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", limit, offset)
	ret0, _ := ret[0].([]*models.LeaderboardEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockLeaderboardServiceMockRecorder) GetLeaderboard(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockLeaderboardService)(nil).GetLeaderboard), limit, offset)
}

// GetUserPosition mocks base method.
func (m *MockLeaderboardService) GetUserPosition(userId string) (*models.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPosition", userId)
	ret0, _ := ret[0].(*models.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPosition indicates an expected call of GetUserPosition.
func (mr *MockLeaderboardServiceMockRecorder) GetUserPosition(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPosition", reflect.TypeOf((*MockLeaderboardService)(nil).GetUserPosition), userId)
}

// RebuildLeaderboard mocks base method.
func (m *MockLeaderboardService) RebuildLeaderboard() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildLeaderboard")
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildLeaderboard indicates an expected call of RebuildLeaderboard.
func (mr *MockLeaderboardServiceMockRecorder) RebuildLeaderboard() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildLeaderboard", reflect.TypeOf((*MockLeaderboardService)(nil).RebuildLeaderboard))
}
