// Code generated by MockGen. DO NOT EDIT.
// Source: scoring_service.go
//
// Generated by this command:
//
//	mockgen -source=scoring_service.go -destination=scoring_service_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	models "github.com/lauralesteves/copa-guru-backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockScoringService is a mock of ScoringService interface.
type MockScoringService struct {
	ctrl     *gomock.Controller
	recorder *MockScoringServiceMockRecorder
	isgomock struct{}
}

// MockScoringServiceMockRecorder is the mock recorder for MockScoringService.
type MockScoringServiceMockRecorder struct {
	mock *MockScoringService
}

// NewMockScoringService creates a new mock instance.
func NewMockScoringService(ctrl *gomock.Controller) *MockScoringService {
	mock := &MockScoringService{ctrl: ctrl}
	mock.recorder = &MockScoringServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoringService) EXPECT() *MockScoringServiceMockRecorder {
	return m.recorder
}

// ScoreMatch mocks base method.
func (m *MockScoringService) ScoreMatch(matchID string) (*models.ScoreResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScoreMatch", matchID)
	ret0, _ := ret[0].(*models.ScoreResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScoreMatch indicates an expected call of ScoreMatch.
func (mr *MockScoringServiceMockRecorder) ScoreMatch(matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScoreMatch", reflect.TypeOf((*MockScoringService)(nil).ScoreMatch), matchID)
}
